spring:
  application:
    name: sensors
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sensors_db
    username: postgres
    password: kali
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
server:
  port: 8085